baseURL = "https://shunkosa.github.io/"
languageCode = "en-us"
title = "Shun Kosaka"
theme = "koa"
disqusShortname = "shunkosa"

[params]
 subtitle = "Things and thoughts about Salesforce and technology"
 navigation = ["about.md", "archives.md"]

[author]
 twitter = "shunkosa"
 facebook = "https://www.facebook.com/shun.kosaka"
 github = "https://github.com/shunkosa"
 npm = "https://www.npmjs.com/~shunkosa"
 qiita = "https://qiita.com/shunkosa"
 speakerdeck = "https://speakerdeck.com/shunkosa"
 salesforce = "https://trailblazer.me/id/shunkosa"
 gravatarEmail = "shun@fastmail.com"
